# -*- coding: utf-8 -*-
"""problem3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wVn3-r5ngrQODAFJDklmTERpVf-eaq2v
"""

import sympy

beta = sympy.symbols('b')
alpha = 2 * sympy.sqrt(2)

L = sympy.Matrix([
 [0,0,0],
 [beta, 0,0],
 [0,beta,0]
])

D = sympy.Matrix([
    [alpha, 0, 0],
    [0,alpha,0],
    [0,0,alpha]
])

U = sympy.Matrix([
    [0,beta,0],
    [0,0,beta],
    [0,0,0]
])

C = (D + L).inv() @ U

C.eigenvals()